# Generated by Django 5.2.17 on 2026-08-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('penalite', 'Pénalité')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée')], default='en_attente', max_length=20)),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=20)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('reference_agregateur', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('donnees_brutes', models.JSONField(blank=True, null=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('coffre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coffres.coffre')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='VerificationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=255)),
                ('expire_a', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_otp', to='transactions.transaction')),
            ],
            options={
                'db_table': 'verifications_otp',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['coffre', 'statut'], name='transaction_coffre__082cca_idx'),
        ),
    ]
