# Generated by Django 5.2.17 on 2026-08-23 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pin_hash', models.CharField(max_length=255)),
                ('montant_cible', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date_deblocage', models.DateField()),
                ('retrait_anticipe_autorise', models.BooleanField(default=False)),
                ('penalite_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('debloque', 'Débloqué'), ('cloture', 'Clôturé')], default='actif', max_length=20)),
                ('solde_cache', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coffres',
                'indexes': [models.Index(fields=['date_deblocage'], name='coffres_date_de_7fa8c1_idx')],
            },
        ),
    ]
